# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 10
    drafts: false
    base_branches:
      - "dev"
      - "staging"
